#spring:
#  application:
#    name: iot-tracking-system
#  config:
#    import: "optional:configserver:http://localhost:8088"


server:
  port: 8081

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

#management:
#  tracing:
#    sampling:
#      probability: 1.0


spring:
  application:
    name: iot-tracking-system